[build]
builder = "NIXPACKS"
buildCommand = "cd dc-circuit-sim-java && ./gradlew clean build -x test"
startCommand = "cd dc-circuit-sim-java && java -Dserver.port=$PORT -jar $(ls build/libs/*-*.jar | head -n 1)"
