[build]
builder = "NIXPACKS"
buildCommand = "chmod +x gradlew && ./gradlew clean bootJar -x test"

[start]
command = "JAR=$(ls build/libs/*.jar | grep -E -v 'plain|original|sources|javadoc' | head -n 1) && echo Running $JAR && java -Dserver.port=$PORT -jar $JAR"

[build.env]
NIXPACKS_SKIP_MISE = "1"
