[build]
builder = "NIXPACKS"
buildCommand = "./gradlew clean build -x test"
startCommand = "java $JAVA_OPTS -Dserver.port=$PORT -jar $(ls build/libs/*-*.jar | head -n 1)"
root = "dc-circuit-sim-java"
