[build]
builder = "NIXPACKS"
buildCommand = "chmod +x gradlew && ./gradlew wrapper --gradle-version 8.7 && ./gradlew clean build -x test"

[start]
command = "java -Dserver.port=$PORT -jar build/libs/*.jar"

[variables]
JAVA_VERSION = "21"
